name: Presubmit
on:
  push:
  pull_request:

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Ninja
        uses: ./.github/actions/setup-ninja
      - name: Checkout repos
        shell: bash
        run: |
          set -x
          android_base=$(mktemp -d)
          external=${android_base}/external
          mkdir ${external}
          for repo in tests/*
          do
            name=$(basename ${repo})
            git init ${external}/${name}
            git -C ${external}/${name} remote add origin $(cat ${repo}/REPO)
            git -C ${external}/${name} fetch --depth 1 origin $(cat ${repo}/VERSION)
            git -C ${external}/${name} checkout $(cat ${repo}/VERSION)
          done
          ndk=android-ndk-r27c
          ndk_zip=${ndk}-linux.zip
          wget https://dl.google.com/android/repository/${ndk-zip}
          unzip -q ${ndk-zip} -d ${ndk}
          cargo run -- ${android_base} $(pwd)/${ndk} all
          for repo in tests/*
          do
            name=$(basename ${repo})
            diff ${repo}/Android.bp ${external}/${name}/Android.bp
          done
